---
title: Double Categories
subtitle: Definitions
date: 08-12-2026
---


:::{.hidden}
$$
\DeclareMathSymbol{\fcmp}{\mathrel}{bbold}{\lq\;}
$$
:::

<!---
::: {.imagify}
$$\fcmp$$
:::
-->

# Definitions

::: {#def-category}
## Category

A Category $C$ consists of the following data:

1. Two classes $C_0$ and $C_1$;

2. Functions $s, t: C_1 \rightarrow C_0$ (the source and target functions);

3. A function $\text{id} : C_0 \rightarrow C_1$ (the function which picks out an identity) such that
$\text{id}$ equalises $s$ and $t$;

4. For every $f, g \in C_1$ such that $t(f) = s(g)$ there is a unique element (there composition) $g \circ f \in C_1$ where
$s(g\circ f) = s(f)$ and $t(g \circ f) = t(g)$.

This data is required to satisfy:

For every $f \in C_1$, we have that $f \circ \text{id}(s(f)) = f$ and $\text{id}(t(f)) \circ f = f$;

For every $f, g, h \in C_1$, we have that $(h\circ g) \circ f = h \circ (g \circ f)$.
:::
<---!
:::::: {#def-double-category}
## Double Category

A [Double Category]{.underline} $\mathbb{C}$ consists of the following data:

1. a Category $\ \mathbb{C}_0 \ $, whose objects we call 0-[cells]{.underline}, and whose arrows we call [tight]{.underline} 1-[cells]{.underline}
$f: V \rightarrow V'$;

2. a Category $\ \mathbb{C}_1 \ $, whose objects we call [loose]{.underline} 1-[cells]{.underline} $M: V \not\rightarrow W$, and whose
arrows we call 2-[cells]{.underline}

::: {.imagify}
[]: %
\begin{tikzcd}
	V && W \\
	& {\Downarrow \phi} \\
	V' && W'
	\arrow["M"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow["f"', from=1-1, to=3-1]
	\arrow["g", from=1-3, to=3-3]
	\arrow["M'"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
\end{tikzcd}
:::

3. two functors $\text{src}, \text{tgt} : \mathbb{C}_1 \rightarrow \mathbb{C}_0$ called [source]{.underline}
and [target]{.underline} respectively;


4. [composition]{.underline} and [identity]{.underline} functors $\circ : \mathbb{C}_1 \times_{\mathbb{C}_0} \mathbb{C}_1 \rightarrow \mathbb{C}_1$ and $\text{id} : \mathbb{C}_0 \rightarrow \mathbb{C}_1$;

5. natural families of isomorphisms in $\mathbb{C}_1$:
-->
::: {.imagify}
[]: %
\begin{tikzcd}
	V && Y \\
	& {\Downarrow a_{P,N,M}} \\
	V && Y
	\arrow["(P\circ N) \circ M"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow[equals, nfold, from=1-1, to=3-1]
	\arrow[equals, nfold, from=1-3, to=3-3]
	\arrow["P \circ (N \circ M)"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
\end{tikzcd}
:::

::: {.imagify}
[]: %
\begin{tikzcd}
	V && W \\
	& {\Downarrow \ell_M} \\
	V && W
	\arrow["\text{id}_W \circ M"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow[equals, nfold, from=1-1, to=3-1]
	\arrow[equals, nfold, from=1-3, to=3-3]
	\arrow["M"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
\end{tikzcd}
:::

::: {.imagify}
[]: %
\begin{tikzcd}
	V && W \\
	& {\Downarrow r_M} \\
	V && W
	\arrow["M \circ \text{id}_V"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow[equals, nfold, from=1-1, to=3-1]
	\arrow[equals, nfold, from=1-3, to=3-3]
	\arrow["M"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
\end{tikzcd}
:::

These data are required to satisfy the following coherence axioms which manifest as equations between composite 2-cells.

The first of these is the following composite,

::: {.imagify}
[]: %
\begin{tikzcd}
	V && Z \\
	& {\Downarrow a_{Q, P, N} \star \text{id}_M} \\
	V && Z\\
    & {\Downarrow a_{Q, P \circ N, M} }\\
    V && Z \\
    & {\Downarrow id_Q \star a_{P, N, M} }\\
    V && Z
	\arrow["((Q \circ P)\circ N) \circ M"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow[equals, nfold, from=1-1, to=3-1]
	\arrow[equals, nfold, from=1-3, to=3-3]
	\arrow["(Q \circ (P \circ N)) \circ M"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
	\arrow[equals, nfold, from=3-1, to=5-1]
	\arrow[equals, nfold, from=3-3, to=5-3]
	\arrow["Q \circ ((P \circ N) \circ M)"'{inner sep=.8ex}, "\shortmid"{marking}, from=5-1, to=5-3]
	\arrow[equals, nfold, from=5-1, to=7-1]
	\arrow[equals, nfold, from=5-3, to=7-3]
	\arrow["Q \circ (P \circ (N \circ M))"'{inner sep=.8ex}, "\shortmid"{marking}, from=7-1, to=7-3]
\end{tikzcd}
:::

is required to be equal to this composite,

::: {.imagify}
[]: %
\begin{tikzcd}
	V && Z \\
	& {\Downarrow a_{Q \circ P, N, M}} \\
	V && Z\\
    & {\Downarrow a_{Q, P, N \circ M} }\\
    V && Z. \\
	\arrow["((Q \circ P)\circ N) \circ M"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow[equals, nfold, from=1-1, to=3-1]
	\arrow[equals, nfold, from=1-3, to=3-3]
	\arrow["(Q \circ P) \circ (N \circ M)"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
	\arrow[equals, nfold, from=3-1, to=5-1]
	\arrow[equals, nfold, from=3-3, to=5-3]
	\arrow["Q \circ ((P \circ N) \circ M)"'{inner sep=.8ex}, "\shortmid"{marking}, from=5-1, to=5-3]
\end{tikzcd}
:::

A further equation is required, which declares that the next composite

::: {.imagify}
[]: %
\begin{tikzcd}
	V && X \\
	& {\Downarrow a_{M, \text{id}_W, N}} \\
	V && X\\
    & {\Downarrow \text{id}_M \star \ell_N}\\
    V && X.
	\arrow["(M \circ \text{id}_W)\circ N"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow[equals, nfold, from=1-1, to=3-1]
	\arrow[equals, nfold, from=1-3, to=3-3]
	\arrow[" M \circ (\text{id}_W \circ N)"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
	\arrow[equals, nfold, from=3-1, to=5-1]
	\arrow[equals, nfold, from=3-3, to=5-3]
	\arrow["M \circ N"'{inner sep=.8ex}, "\shortmid"{marking}, from=5-1, to=5-3]
\end{tikzcd}
:::

is equal to

::: {.imagify}
[]: %
\begin{tikzcd}
	V && X \\
	& {\Downarrow r_M \star \text{id}_N} \\
	V && X.
	\arrow["(M\circ id_W) \circ N"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow[equals, nfold, from=1-1, to=3-1]
	\arrow[equals, nfold, from=1-3, to=3-3]
	\arrow["M \circ N"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
\end{tikzcd}
:::
::::::

Several questions come about when staring at the above definition. If arrows are objects in $\mathbb{C}_1$ what gives the
right to state that they look like arrows with sources and targets that could just as well be source and targets of arrows in $\mathbb{C}_0$.
The source and target functors are lacking defining equations they should be compatible with the composition and identity functors in the way
that is implied from the mantra "double categories are category objects in the category of categories". In particular, the identity functor must
equalise the source and target functors meaning that enrichment is ill-defined or based on evil equality. The more significant problem is that the
presentation of squares need to have a specific orientation which produces conflicts in the literature.

A better definition starts from finding a better definition for categories.

::: {#def-category-indexed}
## Category, indexed version

A category is the data of:

1. A class $C_0$;

2. For every $A, B \in C_0$ a set $C_1(A,B)$;

3. For every $A \in C_0$, a distinguished element $\text{id}_A \in C_1(A,A)$;

4. For every $A, B, C \in C_0$, and every $f \in C_1(A, B)$, as well as $g \in C_1(B,C)$
there is a $g \circ f \in C_1(A,C)$;

satisfying the requirements that

For every $A, B \in C_0$, and every $f \in C_1(A, B)$ the following equations hold

$$f \circ \text{id}_A = f = \text{id}_B \circ f.$$

For every $A, B, C, D \in C_0$, and every $f \in C_1(A, B)$ and also every $g \in C_1(B,C)$ as well as $h \in C_1(C, D)$,
the following equation holds

$$(h \circ g) \circ f = h \circ (g \circ f).$$

The sets $C_1(A,B)$ are pairwise disjoint.
:::

It can be shown through a laborious formal argument that the two definitions, the version with source and target and the indexed version are equivalent and thus we can
use the capitalised or uncapitalised interchangeably.
We would like to have a similar definition for double categories as for the definition of category. The reason to do this is so that there is no confusion in the definition and
data can be expressed clearly.

::: {#def-double-category-indexed}
## Double category, indexed version

A double category $\mathbb{C}$ consists of the following data:

1. A class of objects $\mathcal{O}$ whose members are called the 0-cells of $\mathbb{C}$ (generically upper roman from the end of the alphabet);

2. For every $V, V' \in \mathcal{O}$ a class $\text{hom}_{\tau}(V,V')$, called tight arrows (generically lower roman from the beginning of the alphabet);

3. For every $V, W \in \mathcal{O}$ a class $\text{hom}_{\lambda}(V,W)$ called loose arrows (generically upper roman from middle of the alphabet);

4. For every $V \in \mathcal{O}$ a distinguished tight arrow $1_V \in \text{hom}_{\tau}(V,V)$;

5. For every $V \in \mathcal{O}$ a distinguished loose arrow $id_V \in \text{hom}_{\lambda}(V,V)$;

6. For every $V, V', V'' \in \mathcal{O}$, and every $f \in \text{hom}_{\tau}(V,V')$ and also every $f' \in \text{hom}_{\tau}(V',V'')$, there is a $f \frown f' \in \text{hom}_{\tau}(V,V'')$;

7. For every $V, W, V', W' \in \mathcal{O}$, and every $f \in \text{hom}_{\tau}(V,V'), g \in \text{hom}_{\tau}(W,W')$ and also every $M \in \text{hom}_{\lambda}(V,W), M' \in \text{hom}_{\tau}(V',W')$, there is a set
$\text{wit}(V, W, V', W', f, g, M, M')$ called witnesses (generically lower greek)

<!---
::: {.imagify}
[]: % https://q.uiver.app/#q=WzAsNSxbMCwwLCJYIl0sWzIsMCwiWSJdLFswLDIsIlYiXSxbMiwyLCJXIl0sWzEsMSwiXFxEb3duYXJyb3cgXFxwaGkiXSxbMCwxLCJNIiwwLHsic3R5bGUiOnsiYm9keSI6eyJuYW1lIjoiYmFycmVkIn19fV0sWzAsMiwiZiIsMl0sWzIsMywiTiIsMix7InN0eWxlIjp7ImJvZHkiOnsibmFtZSI6ImJhcnJlZCJ9fX1dLFsxLDMsImciXV0=
\begin{tikzcd}
	V && W \\
	& {\Downarrow \phi} \\
	V' && W'.
	\arrow["M"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow["f"', from=1-1, to=3-1]
	\arrow["g", from=1-3, to=3-3]
	\arrow["M'"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
\end{tikzcd}
:::
-->

8. For every $V, W \in \mathcal{O}$, and every $M \in \text{hom}_{\lambda}(V,W)$ there is a distinguished witness $\upsilon_M \in \text{wit}(V, W, V, W, 1_V, 1_W, M, M)$;

<!---
::: {.imagify}
[]: %
\begin{tikzcd}
	V && W \\
	& {\Downarrow {\upsilon}_N} \\
	V && W.
	\arrow["N"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow["1_V"', from=1-1, to=3-1]
	\arrow["1_W", from=1-3, to=3-3]
	\arrow["N"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
\end{tikzcd}
:::
-->

9. For every $V, W, V', W', V'', W'' \in \mathcal{O}$, and every $f \in \text{hom}_{\tau}(V,V'), f' \in \text{hom}_{\tau}(V',V''), g \in \text{hom}_{\tau}(W,W'), g' \in \text{hom}_{\tau}(W',W'')$
and also every $M \in \text{hom}_{\lambda}(V,W), M' \in \text{hom}_{\lambda}(V',W'), M''\in \text{hom}_{\lambda}(V'',W'')$
as well as every $\phi \in \text{wit}(V, W, V', W', f, g, M, M'), \phi' \in \text{wit}(V', W', V'', W'', f', g', M', M'')$ there is a
$\phi \smile \phi' \in \text{wit}(V, W, V'', W'', f \frown f', g \frown g', M, M'')$.

<!---
::: {.imagify}
[]: %
\begin{tikzcd}
	V && W \\
	& {\Downarrow \phi} \\
	V' && W'\\
    & {\Downarrow \phi'}\\
    V'' && W''. \\
	\arrow["N"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow["f", from=1-1, to=3-1]
	\arrow["g", from=1-3, to=3-3]
	\arrow["N'"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
	\arrow["f'", from=3-1, to=5-1]
	\arrow["g'", from=3-3, to=5-3]
	\arrow["N''"'{inner sep=.8ex}, "\shortmid"{marking}, from=5-1, to=5-3]
\end{tikzcd}
:::


$$\leadsto$$


::: {.imagify}
[]: %
\begin{tikzcd}
	V && W \\
	& {\Downarrow \phi \smile \phi'} \\
	V'' && W''.
	\arrow["M"{inner sep=.8ex}, "\shortmid"{marking}, from=1-1, to=1-3]
	\arrow["f \frown f'"', from=1-1, to=3-1]
	\arrow["g \frown g'", from=1-3, to=3-3]
	\arrow["M''"'{inner sep=.8ex}, "\shortmid"{marking}, from=3-1, to=3-3]
\end{tikzcd}
:::
-->

10. For every $V, W, X \in \mathcal{O}$ and every $M \in \text{hom}_{\lambda}(V,W), N \in \text{hom}_{\lambda}(W,X)$
there is a $N \circ M \in \text{hom}_{\lambda}(V,X)$;

11. For every $V, W, X, V', W', X' \in \mathcal{O}$ and every $f \in \text{hom}_{\tau}(V,V'), g \in \text{hom}_{\tau}(W,W'), h \in \text{hom}_{\tau}(X,X')$
and also every $M \in \text{hom}_{\lambda}(V,W), N \in \text{hom}_{\lambda}(W,X), M' \in \text{hom}_{\lambda}(V',W'), N' \in \text{hom}_{\lambda}(W',X')$
as well as every witness $\phi \in \text{wit}(V, W, V', W', f, g, M, M')$ and $\psi \in \text{wit}(W, X, W', X', g, h, N, N')$ then there is a witness
$\psi \star \phi \in \text{wit}(V, X, V', X', f, h, N \circ M, N' \circ M')$.

12. For every $V, W \in \mathcal{O}$ and every $M \in \text{hom}_{\lambda}(V,W)$ there is
a witness $\ell_M \in \text{wit}(V, W, V, W, 1_V, 1_W, id_W \circ M, M)$. The witness is natural in $M$ in the sense that: for every $M' \in \text{hom}_{\lambda}(V,W)$ and every
$\phi \in \text{wit}(V, W, V, W, 1_V, 1_W, M, M')$ we have

$$\ell_M \smile \phi = (\upsilon_{id_W} \star \phi) \smile \ell_{M'}.$$

Each $\ell_M$ also comes equipped with a friend $k_M \in \text{wit}(V, W, V, W, 1_V, 1_W, M, id_W \circ M)$
such that $k_M \smile \ell_M = \upsilon_M$ and $\ell_M \smile k_M = \upsilon_{id_W \circ M}$;

13. For every $V, W \in \mathcal{O}$ and every $M \in \text{hom}_{\lambda}(V,W)$ there is
a witness $r_M \in \text{wit}(V, W, V, W, 1_V, 1_W, M \circ id_V, M)$. The witness is natural in $M$ in the sense that: for every $M' \in \text{hom}_{\lambda}(V,W)$ and every
$\phi \in \text{wit}(V, W, V, W, 1_V, 1_W, M, M')$ we have

$$r_M \smile \phi = (\phi \star \upsilon_{id_V}) \smile r_{M'}$$

Each $r_M$ comes equipped with a friend $q_M \in \text{wit}(V, W, V, W, 1_V, 1_W, M, M \circ id_V)$
such that $q_M \smile r_M = \upsilon_M$ and $r_M \smile q_M = \upsilon_{M \circ id_V}$;

14. For every $V, W, X, Y \in \mathcal{O}$ and every $P \in \text{hom}_{\lambda}(X,Y), N \in \text{hom}_{\lambda}(W,X), M \in \text{hom}_{\lambda}(V,W)$
there is a witness $a_{P, N, M} \in \text{wit}(V, Y, V, Y, 1_V, 1_Y, (P \circ N) \circ M, P \circ (N \circ M))$. This witness is natural in $P, N$ and $M$ simultaneously
meaning that: for every $P' \in \text{hom}_{\lambda}(X, Y), N' \in \text{hom}_{\lambda}(W, X), M' \in \text{hom}_{\lambda}(V, W)$ and every
$\psi \in \text{wit}(X, Y, X, Y, 1_X, 1_Y, P, P'), \chi \in \text{wit}(W, X, W, X, 1_W, 1_X, N, N'), \phi \in \text{wit}(V, W, V, W, 1_V, 1_W, M, M')$ we have

$$((\psi \star \upsilon_{id_N}) \star \upsilon_{id_M})\smile a_{P', N, M} = a_{P, N, M} \smile (\psi \star (\upsilon_{id_N} \star \upsilon_{id_M})),$$

$$((\upsilon_{id_P} \star \chi) \star \upsilon_{id_M}) \smile a_{P, N', M} = a_{P, N, M} \smile (\upsilon_{id_P} \star (\chi \star \upsilon_{id_M})),$$

$$((\upsilon_{id_P} \star \upsilon_{id_N}) \star \phi) \smile a_{P, N, M'} = a_{P, N, M} \smile (\upsilon_{id_P} \star (\upsilon_{id_N} \star \phi)) $$

Each $a_{P, N, M}$ comes equipped with a friend
$b_{P, N, M} \in \text{wit}(V, Y, V, Y, 1_V, 1_Y, P \circ (N \circ M)), (P \circ N) \circ M)$ such that $a_{P,N,M} \smile b_{P, N, M} = \upsilon_{(P \circ N) \circ M}$ and
$b_{P, N, M} \smile a_{P, N, M} = \upsilon_{P \circ (N \circ M)}$.

This data is required to satisfy the following:

For every $V, V' \in \mathcal{O}$ and every $f \in \text{hom}_{\tau}(V,V')$ we have

$$1_V \frown f = f = f \frown 1_{V'};$$

For every $V, W, V', W', V'', W'', V''', W''' \in \mathcal{O}$ and every $M \in \text{hom}_{\lambda}(V, W), M' \in \text{hom}_{\lambda}(V', W'),
M'' \in \text{hom}_{\lambda}(V'', W''), M''' \in \text{hom}_{\lambda}(V''', W''')$ and also every $f \in \text{hom}_{\tau}(V, V'), g \in \text{hom}_{\tau}(W,W'),
f' \in \text{hom}_{\tau}(V', V''), g' \in \text{hom}_{\tau}(W',W''), f'' \in \text{hom}_{\tau}(V'', V'''),  g'' \in \text{hom}_{\tau}(W'',W''')$ as well as
$\phi \in \text{wit}(V, W, V', W', f, g, M, M'), \phi' \in \text{wit}(V', W', V'', W'', f', g', M', M''), \phi'' \in \text{wit}(V'', W'', V''', W''', f'', g'', M'', M''')$ we have

$$ f'' \frown (f' \frown f) = (f'' \frown f') \frown f,$$

$$ \phi'' \smile (\phi' \smile \phi) = (\phi'' \smile \phi') \smile \phi;$$

For every $V, W, V', W' \in \mathcal{O}$ and every $M \in \text{hom}_{\lambda}(V, W), M' \in \text{hom}_{\lambda}(V',W')$ and also every $f \in \text{hom}_{\tau}(V,V'),
g \in \text{hom}_{\tau}(W,W')$ as well as every witness $\phi \in \text{wit}(V, W, V', W', f, g, M, M')$ we have

$$\upsilon_M \smile \phi = \phi = \phi \smile \upsilon_{M'};$$

For every $V, W, X, Y, Z \in \mathcal{O}$ and every $Q \in \text{hom}_{\lambda}(Y,Z), P \in \text{hom}_{\lambda}(X,Y), N \in \text{hom}_{\lambda}(W, X),
M \in \text{hom}_{\lambda}(V, W)$ we have

$$(a_{Q, P, N} \star id_M) \smile a_{Q, P \circ N, M} \smile (id_Q \star a_{P, N, M}) = a_{Q \circ P, N, M} \smile a_{Q, P, N \circ M};$$

For every $V, W, X \in \mathcal{O}$ and every $N \in \text{hom}_{\lambda}(W, X), M \in \text{hom}_{\lambda}(V, W)$ we have

$$a_{N, id_W, M} \smile (id_M \star \ell_N) = r_M \star id_N.$$
:::
