on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '7 6 * * 1' # Every Monday at 6:07 AM UTC

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Setup TeX Live
        uses: zauguin/install-texlive@v4.4.0
        with:
          packages: scheme-full
          texlive_version: 2025

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
